apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: reloader
  namespace: demo-reloader
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: reloader
  template: 
    metadata: 
      labels: 
        app: reloader 
    spec: 
      serviceAccountName: reloader
      containers: 
      - name: reloader
        image: "ghcr.io/stakater/reloader:v1.0.71"
        ports: 
        - name: http 
          containerPort: 9090 
