---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-reloader
  annotations:
    reloader.stakater.com/auto: "true"
type: Opaque
data:
  POSTGRES_PASSWORD: bmV3cGFzc3dvcmQ=